# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

dist: xenial
os: linux

before_install:
- openssl aes-256-cbc -K $encrypted_d5fbbef4628e_key -iv $encrypted_d5fbbef4628e_iv
  -in lab-devops-cloud-vitor-paiva-83882c5e6c62.json.enc -out ../lab-devops-cloud-vitor-paiva-83882c5e6c62.json
  -d


# Instalação de Módulos que são necessários para a Aplicação.
install:
  - pip install flask

# Defini o script de Teste que deve rodar toda vez que o código for alterado.
script:
  - python -m unittest -v test || travis_terminate 1;

# Definir o Deploy no Heroku
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true 
  app: devopslab-vitor-paiva
  strategy: api

deploy:
  provider: gae
  keyfile: ../lab-devops-cloud-vitor-paiva-83882c5e6c62.json
  project: lab-devops-cloud-vitor-paiva
  on:
     branch: main
